version: '3'

services:
  backend:
      build:
        context: .
        dockerfile: Dockerfile.staging
      command: sh -c "python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:8000 --timeout 90 -k gevent --workers 8 --log-level debug --capture-output"
      ports:
        - 8000:8000
      volumes:
        - .:/usr/app
      env_file: ./.env.staging

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=django_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - database-data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/home/app/web

  celery:
    build:
        context: .
        dockerfile: Dockerfile.staging
    command: sh -c "celery -A config.celery worker -l info"
    env_file: ./.env.staging
    volumes:
      - .:/usr/app
    depends_on:
      - db
      - redis
    restart: on-failure

volumes:
  database-data:
  redisdata: